---
+++
@@ x,24 x,24 @@
     return False


-with trio.move_on_after(10):  # error: 5, "trio", "move_on_after"
-    ...
+# error: 5, "trio", "move_on_after"
+...


 async def function_name():
     # fmt: off
-    async with trio.fail_after(10): ...; ...; ...  # error: 15, "trio", "fail_after"
+    ...; ...; ...  # error: 15, "trio", "fail_after"
     # fmt: on
-    async with trio.fail_after(10):  # error: 15, "trio", "fail_after"
-        ...
-    async with trio.fail_at(10):  # error: 15, "trio", "fail_at"
-        ...
-    async with trio.move_on_after(10):  # error: 15, "trio", "move_on_after"
-        ...
-    async with trio.move_on_at(10):  # error: 15, "trio", "move_on_at"
-        ...
-    async with trio.CancelScope(...):  # error: 15, "trio", "CancelScope"
-        ...
+    # error: 15, "trio", "fail_after"
+    ...
+    # error: 15, "trio", "fail_at"
+    ...
+    # error: 15, "trio", "move_on_after"
+    ...
+    # error: 15, "trio", "move_on_at"
+    ...
+    # error: 15, "trio", "CancelScope"
+    ...

     with trio.move_on_after(10):
         await trio.sleep(1)
@@ x,8 x,8 @@
     with open("filename") as _:
         ...

-    with trio.fail_after(10):  # error: 9, "trio", "fail_after"
-        ...
+    # error: 9, "trio", "fail_after"
+    ...

     send_channel, receive_channel = trio.open_memory_channel(0)
     async with trio.fail_after(10):
@@ x,22 x,22 @@
         async for _ in receive_channel:
             ...

-    async with trio.fail_after(10):  # error: 15, "trio", "fail_after"
-        for _ in receive_channel:
-            ...
+    # error: 15, "trio", "fail_after"
+    for _ in receive_channel:
+        ...

     # fix missed alarm when function is defined inside the with scope
-    with trio.move_on_after(10):  # error: 9, "trio", "move_on_after"
+    # error: 9, "trio", "move_on_after"
+
+    async def foo():
+        await trio.sleep(1)
+
+    # error: 9, "trio", "move_on_after"
+    if ...:

         async def foo():
-            await trio.sleep(1)
-
-    with trio.move_on_after(10):  # error: 9, "trio", "move_on_after"
-        if ...:
-
-            async def foo():
-                if ...:
-                    await trio.sleep(1)
+            if ...:
+                await trio.sleep(1)

     async with random_ignored_library.fail_after(10):
         ...
@@ x,18 x,18 @@
     with trio.fail_after(1):
         with trio.CancelScope():
             await trio.sleep_forever()
-        with trio.CancelScope():  # error: 13, "trio", "CancelScope"
-            ...
+        # error: 13, "trio", "CancelScope"
+        ...
         with trio.CancelScope():
             await trio.sleep_forever()
-        with trio.CancelScope():  # error: 13, "trio", "CancelScope"
-            ...
-
-    with trio.fail_after(1):  # error: 9, "trio", "fail_after"
-        with trio.CancelScope():  # error: 13, "trio", "CancelScope"
-            ...
-        with trio.CancelScope():  # error: 13, "trio", "CancelScope"
-            ...
+        # error: 13, "trio", "CancelScope"
+        ...
+
+    # error: 9, "trio", "fail_after"
+    # error: 13, "trio", "CancelScope"
+    ...
+    # error: 13, "trio", "CancelScope"
+    ...

     with trio.fail_after(1):
         with trio.CancelScope():
@@ x,12 x,12 @@
     # don't remove other scopes
     with contextlib.suppress(Exception):
         print("foo")
-    with trio.fail_after(1):  # error: 9, "trio", "fail_after"
-        with contextlib.suppress(Exception):
-            print("foo")
-    with contextlib.suppress(Exception):
-        with trio.fail_after(1):  # error: 13, "trio", "fail_after"
-            print("foo")
+    # error: 9, "trio", "fail_after"
+    with contextlib.suppress(Exception):
+        print("foo")
+    with contextlib.suppress(Exception):
+        # error: 13, "trio", "fail_after"
+        print("foo")

     with contextlib.suppress(Exception):
         with open("blah") as file:
@@ x,9 x,9 @@


 async def nursery_no_cancel_point():
-    with trio.CancelScope():  # error: 9, "trio", "CancelScope"
-        async with trio.open_nursery():
-            ...
+    # error: 9, "trio", "CancelScope"
+    async with trio.open_nursery():
+        ...


 # but it is a cancel point if the nursery contains a call to start_soon()
@@ x,8 x,8 @@

 async def nursery_start_soon_misnested():
     async with trio.open_nursery() as n:
-        with trio.CancelScope():  # error: 13, "trio", "CancelScope"
-            n.start_soon(trio.sleep, 0)
+        # error: 13, "trio", "CancelScope"
+        n.start_soon(trio.sleep, 0)


 async def nested_scope():
@@ x,22 x,22 @@

 async def nested_function_call():

-    with trio.CancelScope():  # error: 9, "trio", "CancelScope"
-        async with trio.open_nursery() as n:
-
-            def foo():
-                n.start_soon(trio.sleep, 0)
-
-            # a false alarm in case we call foo()... but we can't check if they do
-            foo()
+    # error: 9, "trio", "CancelScope"
+    async with trio.open_nursery() as n:
+
+        def foo():
+            n.start_soon(trio.sleep, 0)
+
+        # a false alarm in case we call foo()... but we can't check if they do
+        foo()


 # insert cancel point on nursery exit, not at the start_soon call
 async def cancel_point_on_nursery_exit():
     with trio.CancelScope():
         async with trio.open_nursery() as n:
-            with trio.CancelScope():  # error: 17, "trio", "CancelScope"
-                n.start_soon(trio.sleep, 0)
+            # error: 17, "trio", "CancelScope"
+            n.start_soon(trio.sleep, 0)


 # async100 does not consider *redundant* cancel scopes
@@ x,32 x,26 @@


 async def autofix_multi_withitem():
-    with trio.CancelScope(), open("foo"):  # error: 9, "trio", "CancelScope"
+    with open("foo"):  # error: 9, "trio", "CancelScope"
         ...

     # this one is completely removed
-    with (
-        trio.CancelScope(),  # error: 8, "trio", "CancelScope"
-        trio.CancelScope(),  # error: 8, "trio", "CancelScope"
-    ):
-        ...
+    # error: 8, "trio", "CancelScope"
+    # error: 8, "trio", "CancelScope"
+    ...

     # these keep the `open`
     with (
-        open("aa") as _,
-        trio.fail_after(10),  # error: 8, "trio", "fail_after"
+        open("aa") as _,  # error: 8, "trio", "fail_after"
     ):
         ...

     with (
-        trio.fail_after(5),  # error: 8, "trio", "fail_after"
-        open("bb") as _,
-        trio.move_on_after(5),  # error: 8, "trio", "move_on_after"
+        open("bb") as _,  # error: 8, "trio", "move_on_after"
     ):
         ...

     with (
-        trio.move_on_after(10),  # error: 8, "trio", "move_on_after"
         open("cc") as f,
     ):
         ...
